language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"
install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install unittest2; fi
    - "pip install -e ."
script:
    - "nosetests tests"
