FIELD_TEXT = 'text'
FIELD_NUMERIC = 'numeric'
FIELD_NO_INPUT = 'none'
FIELD_SELECT = 'select'
FIELD_SELECT_MULTIPLE = 'select_multiple'

FIELD_LIST = [FIELD_TEXT, FIELD_NUMERIC, FIELD_NO_INPUT, FIELD_SELECT, FIELD_SELECT_MULTIPLE]
